
export const GET_PROD_CATEGORIES = "GET_PROD_CATEGORIES"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_PROD_BY_ID = "GET_PROD_BY_ID"
export const GETALLPRODUCTS = "GETALLPRODUCTS";
export const ERROR = "ERROR";
export const GETUSERS = "GETALLUSERS";
export const ORDERPRICE = "ORDERPRICE";
export const ORDERNAME = "ORDERNAME";
export const FILTERTYPE = "FILTERTYPE";
export const FILTERPRICE = "FILTERPRICE";
export const PAGINATION = "PAGINATION";
export const SEARCHPRODUCTS = "SEARCHPRODUCTS";
export const PRODUCTSINCART = "PRODUCTSINCART";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
