export const GETALLPRODUCTS = "GETALLPRODUCTS";
export const ERROR = "ERROR"
export const GET_PROD_CATEGORIES = "GET_PROD_CATEGORIES"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"

