export const GETALLPRODUCTS = "GETALLPRODUCTS";
export const GETUSERS = "GETALLUSERS";
export const GETPRODBYID = "GETPRODBYID";
export const GETPRODCATEGORIES = "GETPRODCATEGORIES";
export const GETPRODUCTBYNAME = "GETPRODUCTBYNAME";
export const CREATEPRODUCT = "CREATEPRODUCT";
export const UPDATEPRODUCT = "UPDATEPRODUCT";
export const DELETEPRODUCT = "DELETEPRODUCT";
export const PAGINATION = "PAGINATION";
export const ORDERPRICE = "ORDERPRICE";
export const ORDERNAME = "ORDERNAME";
export const FILTER = "FILTER";
export const ERROR = "ERROR";
export const POPUPINITIAL = "POPUPINITIAL";

export const GENERATEUSER = "GENERATEUSER"
export const LOGOUT = 'LOGOUT'

export const CLEANSINGLEPROD = "CLEANSINGLEPROD";
export const CLEANSEARCHBAR = "CLEANSEARCHBAR";
export const NAMESEARCH = "NAMESEARCH";
export const TYPEUSER = "TYPEUSER";
